<a href="https://colab.research.google.com/github/rlatldhs123/pandas/blob/main/03_Subset_2)_columns.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### [참고] <a href="https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf">Pandas Cheat Sheet</a>

In [1]:
import pandas as pd

In [2]:
friend_dict_list = [
    {
        "name": "John",
        "age": 25,
        "job": "student",
    },
    {
        "name": "Nate",
        "age": 34,
        "job": "teacher",
    },
    {
        "name": "Jenny",
        "age": 30,
        "job": "developer",
    },
]

friend_df=pd.DataFrame(friend_dict_list)
friend_df

    name  age        job
0   John   25    student
1   Nate   34    teacher
2  Jenny   30  developer

### column 기준
![image.png]()

In [4]:
friend_df.name

0     John
1     Nate
2    Jenny
Name: name, dtype: object

In [5]:
friend_df.age

0    25
1    34
2    30
Name: age, dtype: int64

In [7]:
friend_df[["name","age"]] # 2개부터는 대괄호하나 더 입혀야 함

    name  age
0   John   25
1   Nate   34
2  Jenny   30

#### [실습] student_df 생성
#### 1) DataFrame 생성

   국어  영어  수학
0  15  45  75
1  25  55  85
2  35  65  95

#### 3) 특정 컬럼 조회

In [ ]:
# "국어" 컬럼 가져오기

0    15
1    25
2    35
Name: 국어, dtype: int64

In [ ]:
# "국어" 와 "수학" 컬럼 가져오기

   국어  수학
0  15  75
1  25  85
2  35  95

In [ ]:
# 국어 점수가 20 이상인 컬럼 추출

   국어  영어  수학
1  25  55  85
2  35  65  95

In [ ]:
# 국어 점수가 20 이상인 컬럼 추출

   국어  영어  수학
1  25  55  85
2  35  65  95

In [ ]:
# 국어 점수가 20 이상인데 컬럼은 국어, 영어만 보고 싶다면

   국어  영어
1  25  55
2  35  65